---
engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
  scss-lint:
    enabled: true
exclude_paths:
  - "game/_version.py"
  - "versioneer.py"
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.py"
  - "**.scss"
