#!/bin/bash
set -e
cd "${BASH_SOURCE%/*}"

pip install -e .
pip install 'codeforlife-portal >= 1.0.0.post.dev1' # TODO: Remove this requirement (#688)
./example_project/manage.py migrate --noinput

# Translation/Localisation
pip install 'crowdin-cli-py'
cd game
mkdir -p locale
django-admin makemessages -l en_GB --no-wrap || true
# some files from foundation use '_' for their own purpose
django-admin makemessages -l en_GB --no-wrap -d djangojs --ignore "static/game/js/foundation/*" || true
cd -
./.crowdin-get-translations || true

./example_project/manage.py collectstatic --noinput
./example_project/manage.py runserver "$@"
