#!/bin/bash
set -e
cd "${BASH_SOURCE%/*}"

translation=
while [ "$1" != "" ]; do
  case $1 in
    --with-translation-tools )
      translation=1
      ;;
    * )
      exit 1 # unknown option
      ;;
  esac
  shift
done

./manage.py migrate --noinput

# Translation/Localisation
if [ "$translation" = "1" ]; then
  pip install 'crowdin-cli-py'
  cd game
  mkdir -p locale
  django-admin makemessages -l en_GB --no-wrap
  # some files from foundation use '_' for their own purpose
  django-admin makemessages -l en_GB --no-wrap -d djangojs --ignore "static/game/js/foundation/*"
  cd -
  ./.crowdin-get-translations
fi

./manage.py collectstatic --noinput --clear

./manage.py runserver "$@"

# Uncomment the line below and comment out the one above to run localhost with https.
# Needed for Gitbook embedded content to connect successfully (Python Den).
# Also requires valid certificate files to be had locally.

#./manage.py runserver_plus --cert-file localhost.pem --key-file localhost-key.pem "$@"
