# Generated by Django 5.2.11 on 2026-02-17 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(max_length=200)),
                (
                    "block_type",
                    models.IntegerField(
                        choices=[
                            (0, "Start"),
                            (1, "Action"),
                            (2, "Condition"),
                            (3, "Procedure"),
                            (4, "ControlFlow"),
                            (5, "Variable"),
                            (6, "Math"),
                        ]
                    ),
                ),
            ],
            options={
                "ordering": ["block_type", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("in_development", models.BooleanField(default=False)),
                ("r_random_levels_enabled", models.BooleanField(default=False)),
                ("r_branchiness", models.FloatField(default=0, null=True)),
                ("r_loopiness", models.FloatField(default=0, null=True)),
                ("r_curviness", models.FloatField(default=0, null=True)),
                ("r_num_tiles", models.IntegerField(default=5, null=True)),
                ("r_blockly_enabled", models.BooleanField(default=True)),
                ("r_python_enabled", models.BooleanField(default=False)),
                ("r_traffic_lights", models.BooleanField(default=False)),
                ("r_cows", models.BooleanField(default=False)),
                (
                    "next_episode",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.episode",
                    ),
                ),
                ("r_blocks", models.ManyToManyField(related_name="episodes", to="game.block")),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("path", models.TextField(max_length=10000)),
                ("traffic_lights", models.TextField(default="[]", max_length=10000)),
                ("cows", models.TextField(default="[]", max_length=10000)),
                ("origin", models.CharField(default="[]", max_length=50)),
                ("destinations", models.CharField(default="[[]]", max_length=50)),
                ("default", models.BooleanField(default=False)),
                ("fuel_gauge", models.BooleanField(default=True)),
                ("max_fuel", models.IntegerField(default=50)),
                ("model_solution", models.CharField(blank=True, default="[]", max_length=20)),
                ("disable_route_score", models.BooleanField(default=False)),
                ("disable_algorithm_score", models.BooleanField(default=False)),
                ("threads", models.IntegerField(default=1)),
                ("blockly_enabled", models.BooleanField(default=True)),
                ("python_enabled", models.BooleanField(default=True)),
                ("python_view_enabled", models.BooleanField(default=False)),
                (
                    "theme_name",
                    models.CharField(
                        blank=True,
                        choices=[("grass", "grass"), ("snow", "snow"), ("farm", "farm"), ("city", "city")],
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Van", "Van"),
                            ("Dee", "Dee"),
                            ("Nigel", "Nigel"),
                            ("Kirsty", "Kirsty"),
                            ("Wes", "Wes"),
                            ("Phil", "Phil"),
                            ("Electric van", "Electric van"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("subtitle", models.TextField(blank=True, max_length=100, null=True)),
                ("lesson", models.TextField(default="Can you find the shortest route?", max_length=10000)),
                (
                    "hint",
                    models.TextField(default="Think back to earlier levels. What did you learn?", max_length=10000),
                ),
                (
                    "commands",
                    models.TextField(
                        default='<div class="row"><div class="large-4 columns"><p><b>Movement</b><br>my_van.move_forwards()<br>my_van.turn_around()<br>my_van.turn_left()<br>my_van.turn_right()<br>my_van.wait()<p></div><div class="large-4 columns"><p><b>Position</b><br>my_van.at_dead_end()<br>my_van.at_destination()<br>my_van.at_red_traffic_light()<br>my_van.at_green_traffic_light()<br>my_van.at_traffic_light(c)<br><i>where c is \'RED\' or \'GREEN\'</i></p></div><div class="large-4 columns"><p><br>my_van.is_road_right()<br>my_van.is_road_left()<br>my_van.is_road_forward()<br>my_van.is_road(d)<br><i>where d is \'FORWARD\', \'LEFT\', or \'RIGHT\'</i></p></div></div><div class="row"><div class="large-4 columns"><p><b>Animals</b><br>my_van.is_animal_crossing()<br>my_van.sound_horn()</div></div>',
                        max_length=10000,
                    ),
                ),
                ("anonymous", models.BooleanField(default=False)),
                ("needs_approval", models.BooleanField(default=True)),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="game.episode",
                    ),
                ),
                ("locked_for_class", models.ManyToManyField(blank=True, related_name="locked_levels", to="user.class")),
                (
                    "next_level",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prev_level",
                        to="game.level",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="user.userprofile",
                    ),
                ),
                ("shared_with", models.ManyToManyField(blank=True, related_name="shared", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("finish_time", models.DateTimeField(blank=True, null=True)),
                ("score", models.FloatField(default=0, null=True)),
                ("workspace", models.TextField(default="")),
                ("night_mode", models.BooleanField(default=False)),
                ("python_workspace", models.TextField(default="")),
                ("is_best_attempt", models.BooleanField(db_index=True, default=False)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="user.student",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="game.level"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LevelBlock",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveIntegerField(default=None, null=True)),
                ("level", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="game.level")),
                ("type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="game.block")),
            ],
        ),
        migrations.CreateModel(
            name="LevelDecor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("decor_name", models.CharField(default="tree1", max_length=100)),
                ("level", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="game.level")),
            ],
        ),
        migrations.CreateModel(
            name="Worksheet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lesson_plan_link", models.CharField(blank=True, default=None, max_length=500, null=True)),
                ("slides_link", models.CharField(blank=True, default=None, max_length=500, null=True)),
                ("student_worksheet_link", models.CharField(blank=True, default=None, max_length=500, null=True)),
                ("indy_worksheet_link", models.CharField(blank=True, default=None, max_length=500, null=True)),
                ("video_link", models.CharField(blank=True, default=None, max_length=500, null=True)),
                (
                    "before_level",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="after_worksheet",
                        to="game.level",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worksheets",
                        to="game.episode",
                    ),
                ),
                (
                    "locked_classes",
                    models.ManyToManyField(blank=True, related_name="locked_worksheets", to="user.class"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("contents", models.TextField(default="")),
                ("python_contents", models.TextField(default="")),
                ("blockly_enabled", models.BooleanField(default=False)),
                ("python_enabled", models.BooleanField(default=False)),
                ("python_view_enabled", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspaces",
                        to="user.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="level",
            constraint=models.CheckConstraint(
                condition=models.Q(("default", True), ("needs_approval", True), _negated=True),
                name="level__default_does_not_need_approval",
            ),
        ),
    ]
