# Generated by Django 5.2.12 on 2026-03-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_delete_attempt"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailyactivity",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="dailyactivity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("level", None), _negated=True),
                fields=("date", "level"),
                name="unique_date_level_pair",
            ),
        ),
    ]
