# Generated by Django 3.2.15 on 2022-11-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0075_level_48_houses"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="block_type",
            field=models.IntegerField(
                choices=[
                    (0, "Start"),
                    (1, "Action"),
                    (2, "Condition"),
                    (3, "Procedure"),
                    (4, "ControlFlow"),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
    ]
