# Generated by Django 3.2.16 on 2022-11-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0076_level_locked_for_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='next_level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_level', to='game.level'),
        ),
    ]
