# Generated by Django 3.2.16 on 2022-11-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0076_level_locked_for_class'),
        ('game', '0077_auto_20221106_1608_data'),
    ]

    operations = [
    ]
