# Generated by Django 3.2.16 on 2022-11-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0078_merge_20221127_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['block_type', 'pk']},
        ),
    ]
