# Generated by Django 3.2.20 on 2023-10-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0082_level_43_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='python_view_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
