# Generated by Django 3.2.25 on 2024-06-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0092_disable_algo_score_in_custom_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='aim',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='hint',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='hint_timer_minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='hint_trigger_attempts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='lesson',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
