# Generated by Django 3.2.25 on 2024-06-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0093_alter_level_character_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='subtitle',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='hint',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='lesson',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
