# Generated by Django 3.2.25 on 2024-07-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0094_add_hint_lesson_subtitle_to_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='ideEnabled',
            field=models.BooleanField(default=False),
        ),
    ]
