# Generated by Django 3.2.25 on 2024-07-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0095_level_commands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='commands',
            field=models.TextField(default='<div class="row"><div class="large-4 columns"><p><b>Movement</b><br>my_van.move_forwards()<br>my_van.turn_around()<br>my_van.turn_left()<br>my_van.turn_right()<br>my_van.wait()<p></div><div class="large-4 columns"><p><b>Position</b><br>my_van.at_dead_end()<br>my_van.at_destination()<br>my_van.at_red_traffic_light()<br>my_van.at_green_traffic_light()<br>my_van.at_traffic_light(c)<br><i>where c is \'RED\' or \'GREEN\'</i></p></div><div class="large-4 columns"><p><br>my_van.is_road_right()<br>my_van.is_road_left()<br>my_van.is_road_forward()<br>my_van.is_road(d)<br><i>where d is \'FORWARD\', \'LEFT\', or \'RIGHT\'</i></p></div></div><div class="row"><div class="large-4 columns"><p><b>Animals</b><br>my_van.is_animal_crossing()<br>my_van.sound_horn()</div></div>', max_length=10000),
        ),
    ]
