# Generated by Django 4.2.16 on 2024-11-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0107_rename_worksheet_link_episode_student_worksheet_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="indy_worksheet_link",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
