# Generated by Django 4.2.16 on 2024-12-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0055_alter_schoolteacherinvitation_token"),
        ("game", "0111_create_worksheets"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksheet",
            name="locked_classes",
            field=models.ManyToManyField(
                blank=True, related_name="locked_worksheets", to="common.class"
            ),
        ),
    ]
