# Generated by Django 4.2.18 on 2025-02-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0112_worksheet_locked_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="needs_approval",
            field=models.BooleanField(default=True),
        ),
    ]
