# Generated by Django 5.1.14 on 2025-11-19 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0058_userprofile_google_refresh_token_and_more"),
        ("game", "0117_update_solutions_to_if_else"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("rr_attempt_count", models.PositiveBigIntegerField(default=0)),
                ("pd_attempt_count", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Daily activities",
            },
        ),
        migrations.RemoveField(
            model_name="attempt",
            name="night_mode",
        ),
        migrations.RemoveField(
            model_name="attempt",
            name="python_workspace",
        ),
        migrations.RemoveField(
            model_name="attempt",
            name="workspace",
        ),
        migrations.CreateModel(
            name="LevelMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_spent", models.BigIntegerField(default=0)),
                ("top_score", models.FloatField(default=0)),
                ("attempt_count", models.IntegerField(default=1)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="game.level",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_metrics",
                        to="common.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Levels metrics",
                "unique_together": {("student", "level")},
            },
        ),
    ]
