# Generated by Django 5.1.9 on 2025-05-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0117_update_solutions_to_if_else"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksheet",
            name="starter_code",
            field=models.TextField(default="# Write your code below"),
        ),
    ]
