# Generated by Django 5.1.10 on 2025-09-02 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0117_update_solutions_to_if_else"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("rr_attempt_count", models.PositiveBigIntegerField(default=0)),
                ("pd_attempt_count", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Daily activities",
            },
        ),
    ]
