# Generated by Django 5.1.15 on 2026-02-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0119_aggregate_attempts"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attempt",
        ),
    ]
