name: Snyk

on:
  release:
    types: [published]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    if: github.repository_owner_id == vars.CFL_EDU_ORG_ID
    runs-on: ubuntu-22.04
    steps:
      - name: 🐍 Set up Python 3.12 Environment
        uses: codeforlife-education/codeforlife-workspace/.github/actions/python/setup-environment@main
        with:
          python-version: 3.12

      - name: 🐕‍🦺 Run Snyk Tests
        uses: codeforlife-education/codeforlife-workspace/.github/actions/snyk/run-tests@main
        with:
          snyk-token: ${{ secrets.SNYK_TOKEN }}
          config-path: "backend/.snyk"
          add-test-args: --command=.venv/bin/python
          remove-repo-name-prefix: ""
